name: Build and Push Docker image to Docker Hub

on: push
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs_on: ubuntu-latest
    steps: 
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: actions/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build adn push Docker image
        user: docker/build-push-action@v4
        with:
          context: DockerFolder/
          push: true
          tag: momsomrach1168/gitdockerci:latest
